# Generated by Django 2.0.4 on 2018-04-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180427_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_photo',
            field=models.ImageField(default='accounts/media/user_photo/no_photo.jpg', upload_to='accounts/media/user_photo/'),
        ),
    ]
