# Generated by Django 2.0.4 on 2018-04-23 23:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180423_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date_add',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
