# Generated by Django 2.0.4 on 2018-04-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_date_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='poster',
            field=models.ImageField(blank=True, upload_to='media/genre_poster'),
        ),
    ]
