# Generated by Django 2.0.4 on 2018-04-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180427_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='catalog/static/images/no_cover.jpg', upload_to='book_cover'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='poster',
            field=models.ImageField(blank=True, default='catalog/static/images/no_cover.jpg', upload_to='genre_poster'),
        ),
    ]
