# Generated by Django 2.0.4 on 2018-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180427_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(default='catalog/static/images/no_photo.jpg', upload_to='catalog/media/author_photo/'),
        ),
    ]
